config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'all_notifications/index' => "all_notifications#index"
  get 'all_notifications/list' => "all_notifications#list"
  get 'homepage/homeindex'
  get 'home/index'
  
  mount ActionCable.server => "/cable"
  #devise_for :users, controllers: {  sessions: 'users/sessions'}

  devise_for :users, :controllers => {sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }
  


   
  # root to: 'homepage#homeindex'
  resources :orders do
    resources :details
  end

  get '/addGroup', :controller => 'groups', :action => 'add'
  post '/addGroup', :controller => 'groups', :action => 'addgroup'
  get '/addGroupMember', :controller => 'groups', :action => 'groupmember'
  post '/addMember' , :controller =>'groups' , :action =>'addmember'
  resources :groups
  resources :friends
  delete 'removemember/:id(.:format)', :to => 'groups#removemember'
  delete 'destroy/:id(.:format)' , :to =>'orders#destroy'
  put 'update/:id(.:format)' , :to =>'orders#update'
  #mhdesh yshlhom
  get '/addFriend' , :controller => 'friends', :action => 'add'
  post '/addFriend' , :controller =>'friends' , :action =>'addfriend'
  get '/friendActivity' , :controller => 'home', :action => 'friendactivity'
  # get 'group/delete' , :controller => 'groups', :action => 'delete'

  get '/test', :controller => 'orders', :action => 'test'
  get '/group', :controller => 'orders', :action => 'group'
  post '/save', :controller => 'orders', :action => 'save'
  get '/member', :controller => 'orders', :action => 'member'
  get 'joinedOrder/:name(.:format)', :to => 'orders#joinedOrder'
  #get '/save', :controller => 'orders', :action => 'saveadd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def homeindex
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/homeindex.html.erb
  <nav style="background-color: #c3c3c3de!important;" class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="">
        <%= image_tag("logo4.png" , width: 100) %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">


        </ul>
        <div class="nav-right-side my-2 my-lg-0">
          <%= link_to "Sign in", new_session_path(:user) %>
    
        </div>
      </div>

    </div>
  </nav>
  <!-- end navbar -->
  <main>
    <div class="bg-cover">

      <div class="cd-fixed-bg cd-fixed-bg--1">
        <h1>Are you hungry?</h1>
        <h2>Don't wait!</h2>
        <h2>Let's start to order food now!</h2>

        <div class="secondary-btn">
          <%= link_to 'Register' , registration_path(:user)+"/sign_up", role:"button" , class:"btn btn-outline-danger" %>

        </div>
      </div>

      <div class="hilight"></div>

    </div>

  </main>