config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'all_notifications/index' => "all_notifications#index"
  get 'all_notifications/list' => "all_notifications#list"
  get 'homepage/homeindex'
  get 'home/index'
  
  mount ActionCable.server => "/cable"
  #devise_for :users, controllers: {  sessions: 'users/sessions'}

  devise_for :users, :controllers => {sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }
  


   
  # root to: 'homepage#homeindex'
  resources :orders do
    resources :details
  end

  get '/addGroup', :controller => 'groups', :action => 'add'
  post '/addGroup', :controller => 'groups', :action => 'addgroup'
  get '/addGroupMember', :controller => 'groups', :action => 'groupmember'
  post '/addMember' , :controller =>'groups' , :action =>'addmember'
  resources :groups
  resources :friends
  delete 'removemember/:id(.:format)', :to => 'groups#removemember'
  delete 'destroy/:id(.:format)' , :to =>'orders#destroy'
  put 'update/:id(.:format)' , :to =>'orders#update'
  #mhdesh yshlhom
  get '/addFriend' , :controller => 'friends', :action => 'add'
  post '/addFriend' , :controller =>'friends' , :action =>'addfriend'
  get '/friendActivity' , :controller => 'home', :action => 'friendactivity'
  # get 'group/delete' , :controller => 'groups', :action => 'delete'

  get '/test', :controller => 'orders', :action => 'test'
  get '/group', :controller => 'orders', :action => 'group'
  post '/save', :controller => 'orders', :action => 'save'
  get '/member', :controller => 'orders', :action => 'member'
  get 'joinedOrder/:name(.:format)', :to => 'orders#joinedOrder'
  #get '/save', :controller => 'orders', :action => 'saveadd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @lastOrder = Order.where(user_id: current_user.id).order("id Desc").last(4)
   
    @orders = Order.where(
      user_id: Friend.select("friend_id")
      .where(user_id: current_user.id)
  ).order("id Desc").last(3)

  end

  def friendactivity
    @orders = Order.where(
      user_id: Friend.select("friend_id")
      .where(user_id: current_user.id)
  ).order("id Desc").last(4)
  @test_temp =[]
  for order in @orders 

    @test_temp << {:name => User.find_by_id(order.user_id).username , :meal => order.meal ,:restaurant_name =>order.restaurant_name}
  end
  respond_to do |format|
    format.html
    format.json {render json: @test_temp}
  end
      # respond_to do |format|
      # format.html { redirect_to @orders, notice: 'group was successfully created.' }
      # format.js
      # format.json { head :no_content }
      # end
    
 end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_activity.html.erb
<p>
    <%= User.find_by_id(order.user_id).username %>
        has created an order for
              <%= order.meal %> 
              from
            <%= order.restaurant_name %>
</p>

app/views/home/_header.html.erb
<head>
  <title>Yalanotlob</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
  <link rel="stylesheet" href="style.css">
  <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
        crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-tagsinput/0.8.0/bootstrap-tagsinput.min.js"></script>

</head>

app/views/home/_navbar.html.erb
<div class="groups orderDetails general-cover" style="height: 100%;">

  <!-- end navbar -->
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="">
        <%= image_tag("logo4.png" , width: 100) %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/addFriend">Friends</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/addGroup">Groups</a>

          </li>
          <li class="nav-item">
            <a class="nav-link" href="/orders">Orders</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="/orders">Orders</a>
          </li>

          <li class="nav-item" id="noti_Container">
            <a>
              <div id="noti_Counter"></div>
              <!--SHOW NOTIFICATIONS COUNT.-->

              <!--A CIRCLE LIKE BUTTON TO DISPLAY NOTIFICATION DROPDOWN.-->

              <i class="fa fa-bell fa-lg"></i>

              <!--THE NOTIFICAIONS DROPDOWN BOX.-->
              <div id="notifications">
                <h3>Notifications</h3>
                <div style="height:300px;" id="allNotifications"></div>
                <!--noti. content-->
                <%= link_to "seeAll" ,  all_notifications_index_path %>           
              </div>
            </a>
          </li>

        </ul>
        <div class="nav-right-side my-2 my-lg-0">
        <% !current_user.image.nil? %>
        <%=image_tag(current_user.image, :width => 50, :height => 50, :crop => :fill) %>
        <a href=""><%=current_user.username %></a>
        <div class="test-notifi"></div>
          <a href="#" class="ml-3"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></a>
        </div>
      </div>

    </div>
  </nav>

  <script>
  
  fetch("/all_notifications/list").then((data)=>{
    return data.json();
  }).then((data)=>{
    let dd = document.getElementById("allNotifications");
    var notifications = JSON.parse(JSON.stringify(data));
    notifications[0].forEach((noti)=>{
      let d = document.createElement("div");
      var a = document.createElement("a");
      a.textContent = "accept invitation";
      name = noti.notification.split(" ")[0]
      console.log(name);
      a.setAttribute('href', `/joinedOrder/${name}`);
      d.innerHTML = noti.notification;
      d.appendChild(a)
      dd.appendChild(d);
    });
  });

  </script>

app/views/home/friendactivity.js.erb
$(".user_groups").html("<%= escape_javascript(render :partial => 'activity', :locals => { :orders => @orders }).html_safe %>");

app/views/home/index.html.erb
<body>
<%= render "home/navbar" %>
<div class="all col-md-12">
  <div class="left col-md-6">
    <div class="label">
      Last Orders
    </div>
    <div class="info">
  
    <% @lastOrder.each do |order| %>
<p>
<%= order.meal %> on <%= order.created_at%>
</p>
      
<% end %>     
    </div>
  </div>
  <div class="right col-md-6">
    <div class="label2">
      Friend Activity
    </div>
    <div class="info custom-activity-updates">
          <%= render partial: "activity", collection: @orders , :as => :order  %>
    </div>
  </div>
  

</div>
</body>