config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get 'all_notifications/index' => "all_notifications#index"
  get 'all_notifications/list' => "all_notifications#list"
  get 'homepage/homeindex'
  get 'home/index'
  
  mount ActionCable.server => "/cable"
  #devise_for :users, controllers: {  sessions: 'users/sessions'}

  devise_for :users, :controllers => {sessions: 'users/sessions', :omniauth_callbacks => "users/omniauth_callbacks" }
  


   
  # root to: 'homepage#homeindex'
  resources :orders do
    resources :details
  end

  get '/addGroup', :controller => 'groups', :action => 'add'
  post '/addGroup', :controller => 'groups', :action => 'addgroup'
  get '/addGroupMember', :controller => 'groups', :action => 'groupmember'
  post '/addMember' , :controller =>'groups' , :action =>'addmember'
  resources :groups
  resources :friends
  delete 'removemember/:id(.:format)', :to => 'groups#removemember'
  delete 'destroy/:id(.:format)' , :to =>'orders#destroy'
  put 'update/:id(.:format)' , :to =>'orders#update'
  #mhdesh yshlhom
  get '/addFriend' , :controller => 'friends', :action => 'add'
  post '/addFriend' , :controller =>'friends' , :action =>'addfriend'
  get '/friendActivity' , :controller => 'home', :action => 'friendactivity'
  # get 'group/delete' , :controller => 'groups', :action => 'delete'

  get '/test', :controller => 'orders', :action => 'test'
  get '/group', :controller => 'orders', :action => 'group'
  post '/save', :controller => 'orders', :action => 'save'
  get '/member', :controller => 'orders', :action => 'member'
  get 'joinedOrder/:name(.:format)', :to => 'orders#joinedOrder'
  #get '/save', :controller => 'orders', :action => 'saveadd'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    validates :restaurant_name, presence: true,
                    length: { minimum: 3 }
    validates :meal, presence: true
    has_many :orders_users, dependent: :delete_all
  
    has_many :order_details
    belongs_to :user
    acts_as_taggable_on :tags
    mount_uploader :menu_image, ImageUploader
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

require 'will_paginate/array'
def index

    @orders = Order.where(user_id: current_user.id).paginate page: params[:page], per_page: 2
    @invited = OrdersUser
    # @newOrder = OrdersUser.where(user_id: current_user.id).inspect
end
    

    def destroy
        @orders = Order.find(params[:id])
        @orders.destroy
        redirect_to orders_path
        end
     
        def update
            @order = Order.find(params[:id])
            p params[:id];
            @order.update(status: 1)
            redirect_to orders_path
        end
  
    def new
        @order = Order.new
    end

    def create 
        #logger.debug "\n#{params[:tags]}\n";
        @order = Order.new({"meal"=>order_params[:meal] , "restaurant_name"=>order_params[:restaurant_name] ,"menu_image"=>order_params[:menu_image] })
        @order.user_id = current_user.id
        @order.status=0
        @order.save
        @owner=current_user.username
        if @order.save
          #  logger.debug "\n#{params[:friends}\n";
           #logger.debug "\n#{order_params[:friends]}\n";

           for friend in order_params[:friends]
            @user = User.where(:username => friend).first
            @ordersUser = OrdersUser.new({"order_id"=> @order.id ,"user_id"=> @user.id ,"joined"=> 0})
            @ordersUser.save
            @notify=@owner +" invited you to join his order from "+@order.restaurant_name;
            
            @notification = Notification.new({"user_id"=>@user.id,"notification"=>@notify,"status"=>0})
            @notification.save

            end
           
            redirect_to "/orders/#{@order.id}/details"
        else
            render 'new'
        end
       
    end

    def test
        @user = User.find(current_user.id)
        @friends = @user.users
        @customFriends = []
        for friend in @friends
            es = User.where("id = ?", friend.friend_id).first
                @customFriends << es
        end
     
        respond_to do |format|
          format.html
          format.json {render json: @customFriends}
        end
    end


    def member
        @gId = Group.where("name = ?",params[:id] ).first
        @group = Group.find(@gId.id)
        @members = @group.members
        respond_to do |format|
            format.html
            format.json {render json: @members}
          end
  
    end

    def group
     
        @user = User.find(current_user.id)
        @groups = @user.groups
        respond_to do |format|
          format.html
          format.json {render json: @groups}
        end
    end
    

  

    def joinedOrder 
        puts "-----------------"
        @user = User.where(:username => params[:name]).first
        
        @order = Order.where(:user_id => @user.id).order('created_at DESC').first
        @orderUser = OrdersUser.where("order_id = ? AND user_id = ?", @order.id, current_user.id)
        @orderUser.update(joined: 1)
        redirect_to "/orders/#{@order.id}/details"
    end

    def show
        @order = Order.find(params[:id])
    end

    private
    def order_params
        params.require(:order).permit(:restaurant_name, :meal,:menu_image,:friends => {})
        
    end


end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<body>
<%= render "home/navbar" %>
<div class="container">
  <div class="left col-md-6">
 
      <h2> My Orders</h2>
  
  </div>
  <div class=" col-md-6 right">
    <div class="new">

    
       <%= link_to "Start new Orders", {:controller => "orders", :action => "new"},class: "start" ,:"data-turbolinks"=> "false"%>
    
    </div>
  </div>
  <div class="tablecontant col-md-">
 
 
    <table class="table  col-md-12">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Order</th>
          <th scope="col">Resturnats</th>
          <th scope="col">Invited</th>
          <th scope="col">Joined</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>

        </tr>
      </thead>
      <tbody class="tb">
      <% @orders.each do |order| %>
        <tr>
        
        <td><%= order.meal %></td>
        <td><%= order.restaurant_name %></td>
        <td><%= @invited.where(order_id: order.id).count %></td>
        <td><%= @invited.where(order_id: order.id, joined: 1).count %></td>
        
        <% if order.status == true %>
        <td> finished </td>
        <% else %>
        <td> wating </td> 
        <% end %>
          <td>

          <%if order.status == false %>
           
          <%= button_to order_path(order), 
          method: :put,class: "btn",
          data: { confirm: 'Are you sure?' } , form: {style: 'display:inline-block;margin:0'} do %>
            <i class="fas fa-2x fa-check-circle"></i>
         <% end %>
           
            <%= button_to order_path(order),
            method: :delete,class: "btn",
            data: { confirm: 'Are you sure?' } , form: {style: 'display:inline; margin:0'} do %>
              <i class="fas fa-2x fa-times-circle"></i>
               <% end %>
             <% end %> 
       
             <%= button_to order_details_path(order),
             method: :get,class: "btn",
             form: {style: 'display:inline-block;margin:0'} do %>
              <i class="far fa-2x fa-eye"></i>
<% end %>


       </td>
        </tr> 

        <% end %>
      </tbody>
   
    </table>
  <div style="margin-left:40%">
    <%= will_paginate @orders, renderer: WillPaginateSemanticUi::ActionView::Renderer%>
  </div>

  </div>
  </div>
</div>
  <script type="text/javascript" src="//use.typekit.net/psm0wvc.js"></script>
  <script type="text/javascript">try { Typekit.load(); } catch (e) { }</script>
  <script src="js/jquery-3.3.1.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>

</html>

app/views/orders/new.html.erb
<%= render "home/navbar" %>
<%= form_with model: @order, :id =>"create_new_order" , local: true do |form| %>
   
   <div class="group-content add-orders">
            <div class="container">
                <br><br>
                <div class="row">
                                <div class="col-12">
                                    <h1>Add Order</h1>
                                </div>
                            </div>
                            <br>

            <div class="row">
            <div class="col-8">
    <span class="ownername"><%=current_user.username%></span>
      <p class="field">
 <div class="row"> 
                  <div class="col-4"> 
        <%= form.label :restaurant_name %><br>
</div>
                  <div class="col-8">
        <%= form.text_field :restaurant_name , :class=>'rest-name' %>
 </div>
                </div>
              </p>
     
      <p class="field">
      <%= form.label :meal %><br>
      <%= select(:order, :meal, [['breakfast'], ['dinner'], ['lunch'],['snack']]) %>
      </p>
   <div class="row">
                <div class="col-4">
                <label for="example-text-input" class="col-2 col-form-label">Menu Image:</label>
                </div>

                <div class="col-8">
      <%= form.file_field :menu_image %>
</div>
                </div>



              <div class="row">
                <div class="col-4">

                <label  class="col-2 col-form-label" for="tags">Friends: </label>
              </div>

              <div class="col-8">
                <input id="tags">
              </div>
		<div class="col-12">
		 <span onclick="sendNoification()" class="send" style="border:1px solid #fff;color:#fff;"> Send Invitations 			</span>
		</div>
                  </div>


              <div class="row">
                  <div class="col-4">
                  </div>
                  <div class="col-8">
                      <div style="text-align: right;" class="secondary-btn">
                            
                          <div class="mybutton">
                            <p>
                              <%= form.submit %>
                            </p>
                          </div>

                      </div>
                  </div>
              </div>

              <% end %>

            </div>
 <div class="col-4">
<div class="fiends-invited">
            <div class="row">
                <h4>Friends invited</h4>
                <div class="col-12">
                    <div class="span4">
                        <img class="img-left" width="60" src="images/character.png" />
                        
                        <div id="invite-list">
                          <ul>
                          </ul>
                        </div>

                    </div>

                </div>
            </div>
        </div>



            </div>


            </div>
            </div>
            </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script>
    $("#create_new_order").submit(function() {
        sendNoification()
      });
    </script>

app/views/orders/show.html.erb
<%= @order.restaurant_name %>
<%= @tags %>
<%= image_tag(@order.menu_image.to_s) %>